version: '3'
services:
  solr_node1:
    container_name: solr_node1
    image: solr:9.0.0
    ports:
      - "8080:8983"
    volumes:
      - "./solr/solr.in.sh:/etc/default/solr.in.sh"
      - "./solr/conf:/opt/solr/server/solr/configsets/ldgourmet/conf"
      - "./solr/logs:/var/solr/logs"
    command:
      - "-Denable.packages=true"
    restart: always
    depends_on:
      - zookeeper1
    links:
      - "mysql"
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ldgourmet
      - MYSQL_USER=solrtutorial
      - MYSQL_PASSWORD=solrtutorial
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data/ldgourmet:/data/ldgourmet"
      - "./mysql/sql/:/docker-entrypoint-initdb.d/"
      - "./mysql/conf.d:/etc/mysql/conf.d"
  zookeeper1:
    image: zookeeper:3.6
    container_name: zookeeper1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
